language: python

install:
- pip install tox
script: tox

jobs:
  include:
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=py38
  - python: '3.9'
    env: TOXENV=py39
  - python: '3.8'
    env: TOXENV=flake8
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    env:
    install:
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: iCbsT8YZDa96g2IBDIYKV918lDJOnO4WIqxdoDPh9Z7H7aq9EoAD00r6dTfyi8p/F/e+QCflB5BsG3w9DgVEydzz63qDMpOA5cFoHtkwnl1zRrVdR3ER5eoS37QrrHwZowFLEKbbOVv2KSYk387Ovg+92w1nEziv6GHr0ZnzuNxoO2uUEERA40skW7cZFBq0renhFI8a/l0U3jmwtprxsSeuYGWUk59NiTC3tOfW3/i+WzZdQlUFl+WEZtN7IM2KLGM7hM3vWeC5OPoQdLMZiJG/HtzacGPDETcKPkqEbgDpv65INAhEeCy4Ypwkue4V/irbraTpjVVCh0ARZT8WyX7nm8K+oKPgMvFpHXFP8Fccyq/Ni0Fw2tJWXp+Xmw1Fo1yC6GxWAEX9zJ5hZ3RMQOHX+yqzl8qJJrwxYncGQgIS43UkpcdChtE7gFeaRONhlRkpXKrHU2zh0lckZqE/DQz+O1RYVXGJYNvHxT5gMPKU/mOmwKNfmQfI/HfVwtzPgiSnEvddSYIRe2K6fndp6EWEiCViTEP1/l+S1licKcnf1SAYllisxW7ghDWgEN/736gu1Qg+yb6tRyYxy59imG513XdULbHCX+Aswvq3VztnXHxceAYXTmifozOITgx8Uh+dqNfRvPMafTWD6bIWSw73xf/AjsMqNDjF0RH5p10=
      on:
        tags: true
