language: python
python: 3.6
sudo: required
env:
- TOXENV=py3
- TOXENV=docs
- TOXENV=flake8
install:
- sudo apt install python3-dev
- sudo apt install linux-headers-$(uname -r)
- ls -l /usr/include/linux
#- sudo apt install python3-evdev
- pip install tox
script: tox
jobs:
  include:
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    env:
    install:
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: iCbsT8YZDa96g2IBDIYKV918lDJOnO4WIqxdoDPh9Z7H7aq9EoAD00r6dTfyi8p/F/e+QCflB5BsG3w9DgVEydzz63qDMpOA5cFoHtkwnl1zRrVdR3ER5eoS37QrrHwZowFLEKbbOVv2KSYk387Ovg+92w1nEziv6GHr0ZnzuNxoO2uUEERA40skW7cZFBq0renhFI8a/l0U3jmwtprxsSeuYGWUk59NiTC3tOfW3/i+WzZdQlUFl+WEZtN7IM2KLGM7hM3vWeC5OPoQdLMZiJG/HtzacGPDETcKPkqEbgDpv65INAhEeCy4Ypwkue4V/irbraTpjVVCh0ARZT8WyX7nm8K+oKPgMvFpHXFP8Fccyq/Ni0Fw2tJWXp+Xmw1Fo1yC6GxWAEX9zJ5hZ3RMQOHX+yqzl8qJJrwxYncGQgIS43UkpcdChtE7gFeaRONhlRkpXKrHU2zh0lckZqE/DQz+O1RYVXGJYNvHxT5gMPKU/mOmwKNfmQfI/HfVwtzPgiSnEvddSYIRe2K6fndp6EWEiCViTEP1/l+S1licKcnf1SAYllisxW7ghDWgEN/736gu1Qg+yb6tRyYxy59imG513XdULbHCX+Aswvq3VztnXHxceAYXTmifozOITgx8Uh+dqNfRvPMafTWD6bIWSw73xf/AjsMqNDjF0RH5p10=
      on:
        tags: true
